apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocm-agent-operator
  namespace: openshift-ocm-agent-operator
rules:
- apiGroups:
  - ""
  resources:
  - services
  - services/finalizers
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/finalizers
  - replicasets
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ocmagent.managed.openshift.io
  - ocmagent.managed.openshift.io/finalizers
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
    - networking.k8s.io
  resources:
    - networkpolicies
    - networkpolicies/finalizers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
